name: psltool-fmt

on:
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write # If you run this on an untrusted PR, will it be able to
  # write to the repo?

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "stable"
      - name: run validations
        run: |
          cd tools
          go run ./psltool fmt ../public_suffix_list.dat
      - name: create PR
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Apply formatting using `psltool fmt`
          branch: psltool-fmt
          title: 'Automatic PR for formatting workflow using `psltool fmt`'
          body: 'Automatic PR for formatting workflow using `psltool fmt`'